### ISSUE TITLE
Ayuda, Trato de ejecutar codigo pero no encuentro libreria

### ISSUE THREAD

**Issue by claudiomirandap** [niclabs/DTE#11]
Hola gente, 
Trato de ejecutar el codigo pero no me resulta, muchas de las clases me pide la clase cl.sii.siiDte.GetTokenDocument;  y no puedo encontrala, si pudieran ayudarme les estaria muy agradecido.

**Comment by madestro** [comment]
Hola Claudio, lamentablemente desde el 1 de enero de este año ya no damos soporte a la librería.  Sólo mantenemos el repositorio.
