### ISSUE TITLE
Lista de correo

### ISSUE THREAD

**Issue by leus** [niclabs/DTE#2]
Al parecer  la lista "dte@niclabs.cl" no está funcionando.

> Mail Delivery Subsystem mailer-daemon@googlemail.com
> 7:56 PM (4 minutes ago)
> 
> to me 
> Hello leonardo.herrera@gmail.com,
> 
> We're writing to let you know that the group you tried to contact (dte) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
> - You might have spelled or formatted the group name incorrectly.
> - The owner of the group may have removed this group.
> - You may need to join the group before receiving permission to post.
> - This group may not be open to posting.
> 
> If you have questions related to this or any other Google Group, visit the Help Center at http://www.google.com/support/a/niclabs.cl/bin/static.py?hl=en_US&page=groups.cs.
> 
> Thanks,
> 
> niclabs.cl admins

**Comment by madestro** [comment]
fixed
