### ISSUE TITLE
URIReferenceException / Cannot resolve element with ID

### ISSUE THREAD

**Issue by kripper** [niclabs/DTE#4]
José:

Esta versión genera el siguiente problema al validar DTEs:

Firma XML Incorrecta
Documento: Timbre OK
Documento: Estructura XML OK
Documento: Firma XML Incorrecta: No se pudo verificar la firma XML: javax.xml.crypto.URIReferenceException: com.sun.org.apache.xml.internal.security.utils.resolver.ResourceResolverException: Cannot resolve element with ID NXXX

OBS: Los IDs en el XML ahora deben definirse como tales en forma explícita en el schema o programáticamente con setIdAttribute()

**Comment by andyveliz** [comment]
Lo que describes es un cambio que ocurrió en Java, por lo que es recomendable que sigas utilizando la última versión compatible 1.7 update 21

**Comment by pinkyxw** [comment]
hola estoy bastante perdido, en varias clases se importa cl.sii... pero no se de donde sacar eso.
algún consejo para orientarme un poco ?
