### ISSUE TITLE
Firma Timbre Electronico Incorrecta al recompilar última versión

### ISSUE THREAD

**Issue by pabloruizfaundez** [niclabs/DTE#6]
Buenas, con que JDK hay que compilar la última versión de DTE, ya que me genera error al generar la librería

**Comment by madestro** [comment]
es recomendable que sigas utilizando la última versión compatible 1.7 update 21

**Comment by pabloruizfaundez** [comment]
Efectivamente ahora me funciona. Pero hay un problema al usar el soporte para recepción de mercaderías con la última actualización, aparece error en firma.
