### ISSUE TITLE
Cual es el password para ejecutar el certificado?

### ISSUE THREAD

**Issue by diegosep** [niclabs/DTE#9]
Estoy tratando de ejecutar los ejemplos pero no encuentro el password para "contribuyente1.p12"

Gracias :)

**Comment by madestro** [comment]
Hola, ¿ese ejemplo no usa certificados?

**Comment by diegosep** [comment]
en los ejemplos que hay para ejecutar por linea de comandos, se debe pasar el certificado y el password, yo puse el nombre del certificado que viene en la carpeta del proyecto, por si tuvieran el pass ya que no tengo certificado propio.

**Comment by madestro** [comment]
Chequeo y te aviso, estoy retomando la mantención de la librería y ya me he encontrado con varios problemas de este tipo.

**Comment by diegosep** [comment]
Gracias, yo he tomado algunas cosas de su código para pruebas locales y les he añadido Spring Boot y montado en tomcat mediante un servicio. Por el momento funciona bien :).

EDIT 1: he conseguido un certificado y va bien. :+1:

**Comment by madestro** [comment]
ok, lo cierro entonces.
